URL指定でconfigを読み込む
aigidjp/simple-geo-viewer pull request #73
Opened 2022-07-12 08:50 UTC by DevKoukiMaeda

タイトル通り #71

2022-07-12 09:38 UTC, DevKoukiMaeda commented
カスタムフックの実装では無い理由ですが、getMenuの実行で
毎回menu.jsonにリクエストが飛んでしまうためです。

2022-07-15 02:15 UTC, DevKoukiMaeda commented
コンテキストで実装しました

2022-07-15 19:49 UTC, Kanahiro requested changes

2022-07-15 19:49 UTC, Kanahiro commented on src/pages/index.tsx
> +  let initialViewjson :any = {};
JSONの状態はuseStateで管理されているため、別に変数を保持する必要はないでしょう。

2022-07-15 19:49 UTC, Kanahiro commented on src/pages/index.tsx
> +      setInitialView(initialViewjson);
同上で、~~jsonという変数を経由する必要がないと思います。

2022-07-15 19:49 UTC, Kanahiro commented on src/pages/index.tsx
> +  setInitialView: React.Dispatch<React.SetStateAction<any>>;
これらのstateは、個別のJSONを読み込まれた結果であるものの、そのいずれかが欠けてもこのアプリケーションは動作しません。
これらを集約するひとつのObjectとなっていた方が、管理がしやすくなるでしょう。

```typescript
// イメージ
// 設定を意味するconfigやsettingsという言葉がすでに使われてしまっているので、preferenceという言葉を使っている
const appPreference = {
  backgrounds: {},
  config: {},
  initial_view: {},
  menu: {},
  settings: {}
}
```

2022-07-15 19:49 UTC, Kanahiro commented on src/pages/index.tsx
> +    setInitialView
子コンポーネントでJSONから取得した設定値を更新されては困るので、set~~()は外部に晒さない方が安全でしょう。

2022-07-15 19:49 UTC, Kanahiro commented on src/components/LayerFilter/jsonLoad.ts
> +export default async function jsonLoad(config:any,jsonPath:string):Promise<any> {
開発サーバーをローンチすると、この関数で実行時エラーが発生します。

2022-07-19 00:57 UTC, merged